version: '3.8'

services:
  redmine:
    image: redmine:5.0
    container_name: redmine-test
    ports:
      - "3000:3000"
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_PASSWORD: password
      REDMINE_DB_DATABASE: redmine
      REDMINE_DB_USERNAME: redmine
    volumes:
      - redmine_files:/usr/src/redmine/files
      - redmine_logs:/usr/src/redmine/log
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: redmine-postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: redmine
      POSTGRES_USER: redmine
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  redmine_files:
  redmine_logs:
  postgres_data: 